### PR TITLE
CDP-671: Verify article feed module does not break with new API

### PR DESCRIPTION
**Pull request by bit-saver**
Changed id to post_id where referenced.
Changed taxonomies to custom_taxonomies to match new schema.
Changed article.featured_image to article.thumbnail to match new schema.
Augmented appendQry to react differently when given an array of fields (ORs them together now).
Augmented reduceQry to parenthesize groupings.

### CODE REVIEW

**Comment by terriregan** [comment]
I am not sure if this was an issue before, but can you check to see why tags are not appearing in the display when 'tags' is added to the incoming config meta array:
`meta: ['tags', 'author', 'date']`

That array tells the UI what to display

**Comment by bit-saver** [comment]
I failed to update the getTags function to use the new schema.  It was expecting tags to be objects containing name and id properties.  I updated it to use tag as a string if it does not find object properties.

**Comment by terriregan** [comment]
One more: `Warning: flattenChildren(...): Encountered two children with the same key, `english`. Child keys must be unique; when two children share a key, only the first child will be used.`

**Comment by bit-saver** [comment]
Looks like a language index issue.  Though I don't know why they'd have a key of 'english'.  Does it reference where in the code that gets used?

**Comment by terriregan** [comment]
In React, any iterable display list has to have a unique id.  Error is in `list_default_item.jsx:48` and `list_blog_item.jsx:48`.  I would suggest importing a library like uuid (https://www.npmjs.com/package/uuid) to add a unique key to each <span>.  Looks like you are interating about the tags

**Comment by bit-saver** [comment]
Added uuids to tag elements when no tag.id is present.

**Pull request merged**
